# values.yaml for Traefik Helm Chart

# Configure the service to use an external load balancer with a static IP
service:
  enabled: true
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "External"
  loadBalancerIP: "34.76.171.97"  # Replace with your reserved static IP

# Configure entry points for HTTP and HTTPS
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Enable Traefik dashboard (optional)
api:
  dashboard: true
  insecure: true  # Set to false and secure with authentication in production

# Enable the Traefik provider for Kubernetes CRD
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

# Configure Let's Encrypt for automatic HTTPS (optional)
certificatesResolvers:
  letsencrypt:
    acme:
      email: "oheneralov@gmail.com"  # Replace with your email address
      storage: "/data/acme.json"
      httpChallenge:
        entryPoint: "web"

# Enable logging
logs:
  general:
    level: "INFO"  # Set to "DEBUG" if you need more verbose logs
  access:
    enabled: true

# Deployment settings
deployment:
  replicas: 1
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 65532
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532

# Configure RBAC (Role-Based Access Control)
rbac:
  enabled: true

# Enable persistence for Let's Encrypt certificates
persistence:
  enabled: true
  path: "/data"
  size: 128Mi
  accessModes:
    - ReadWriteOnce
  storageClass: "standard"  # Use default storage class or specify one

# Metrics (optional, e.g., for Prometheus)
metrics:
  prometheus:
    enabled: false

# TLS Options (optional, if you want to customize TLS settings)
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true
