{{- if .Values.metrics.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm-dir.fullname" . }}-metrics
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "helm-dir.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm-dir.fullname" . }}-metrics
  minReplicas: {{ .Values.metrics.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.metrics.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.metrics.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.metrics.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.metrics.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.metrics.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
