{{- if .Values.monitoring.serviceMonitor.enabled }}
{{- if .Values.mainwebsite.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm-dir.fullname" . }}-mainwebsite
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "helm-dir.labels" . | nindent 4 }}
    app.kubernetes.io/component: mainwebsite
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "helm-dir.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mainwebsite
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
{{- end }}

{{- if .Values.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm-dir.fullname" . }}-metrics
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "helm-dir.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "helm-dir.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
{{- end }}
{{- end }}

