apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: 
    server: https://34.78.111.104
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: jenkins-sa
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkR4UDJ3VE9FVnI4RXRzQTg4TzdZejV1dWdvMlV2TDdDVk9kTG5sVmxmNDQifQ.eyJhdWQiOlsiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvY2xldmVyLXNwaXJpdC00MTcwMjAvbG9jYXRpb25zL2V1cm9wZS13ZXN0MS1kL2NsdXN0ZXJzL21pY3Jvc2VydmljZXMtY2x1c3RlciJdLCJleHAiOjE3MzQ5NzM4OTYsImlhdCI6MTczNDk3MDI5NiwiaXNzIjoiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvY2xldmVyLXNwaXJpdC00MTcwMjAvbG9jYXRpb25zL2V1cm9wZS13ZXN0MS1kL2NsdXN0ZXJzL21pY3Jvc2VydmljZXMtY2x1c3RlciIsImp0aSI6IjdkYTBjOGI4LWE0MzktNDI3Yi1hNWUwLTIwYWQ1YzNiMTU4MiIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoiZGVmYXVsdCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJqZW5raW5zLXNhIiwidWlkIjoiNmEzMmRmZjItOWJjYy00OTg3LWEzODAtNjM4MjJmMzgzMGEyIn19LCJuYmYiOjE3MzQ5NzAyOTYsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMtc2EifQ.jiy1dYQ0JQtB6zfVNsyGASz-0YRjh-cwCU6RANqRX0X6M0t1k2guAiGmOt7FR8h_uNLT56BI8jOFgiUDz55QrmOH0EMg3Xoq7Gw6zInEVe6jXBtUH4rRKofhapxrYXu4v4dqkwPhr6A2W6DJN4Rmwz-B4ZZSbZ09mqMpKB_pwFeSf8JMY6GTOsAs16essw7r-oXQZzEPr5pm60UVdHa66KN32937L3KHnRP11Zl3vZo7YHzm0m-xt_J8r_1pQ-jK_BqaXKotnszEfniF-zpNGkHk9wi3mDU6mulmr9ij5IUG0_ng8YH9CsCRALTWwxnFxKHwauXmDpQ8NvlhTRQV9A
