name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-nodejs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean and install dependencies
        working-directory: service1
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --no-audit --no-fund

      - name: Run unit tests
        working-directory: service1
        run: npm test


  terraform-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install tfsec (Terraform security scanner)
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec security scan
        run: tfsec ./terraform
